[package]
name = "rrpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
# rpm = "0.12.1"
rpmrepo_metadata = "0.2.0"
url = "2.4.1"
